version: '3.8'
services:
  grafana:
    image: grafana/grafana:latest
    user: ${MONITOR}
    container_name: grafana
    restart: unless-stopped
    expose:
      - 3000      
    ports: 
      - 3000:3000  
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}  
      - GF_USERS_ALLOW_SIGN_UP=false
  
  node-red:
    image: nodered/node-red
    container_name: node-red
    user: ${MONITOR}
    environment:
      - TZ=Europe/Moscow
    ports:
      - "1880:1880"
    volumes:
      - "./node-red:/data"
    networks:
      - monitoring
    restart: always

    networks:
        monitoring:
        driver: bridge
    
volumes:
    grafana: {}
    node-red: {}

    