version: '3.3'
services:
  grafana:
    image: grafana/grafana:8.0.6
    user: ${MONITOR}
    container_name: grafana
    expose:
      - 3000      
    ports: 
      - 3000:3000  
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_LOGIN=${GF_SECURITY_ADMIN_LOGIN}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}  
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - influxdb
    networks:
      - nodered-stack-networks  
    restart: unless-stopped

  node-red:
    image: nodered/node-red:1.3.5
    container_name: node-red
    user: ${MONITOR}
    environment:
       - TZ=Europe/Moscow
    ports:
       - "1880:1880"
    volumes:
       - ./node-red:/data
    links:
      - influxdb
    networks:
      - nodered-stack-networks  
    restart: always

  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.4
    container_name: influxdb
    user: ${MONITOR}
    ports:
       - "8086:8086"
    volumes:
       - ./influxdbv2:/root/.influxdbv2
    environment:   
       - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
       - INFLUXDB_ORG=${INFLUXDB_ORG}
       - INFLUXDB_ADMIN_LOGIN=${INFLUXDB_ADMIN_LOGIN}
       - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    networks:
       - nodered-stack-networks    
    restart: unless-stopped
  
  influxdb_cli:  
    image: quay.io/influxdb/influxdb:v2.0.4
    container_name: influxdb_cli
    user: ${MONITOR}
    volumes: 
      - ./entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh:ro
    depends_on:
      - influxdb
    # links:
    #   - influxdb  
    networks:
      - nodered-stack-networks  
    restart: on-failure:10
  
networks:
  nodered-stack-networks:
   driver: bridge
    
volumes:
    grafana: {}
    node-red: {}
    influxdbv2: {}
  

