version: '3.3'
services:
  grafana:
    image: grafana/grafana:8.0.6
    user: ${MONITOR}
    container_name: grafana
    restart: unless-stopped
    expose:
      - 3000      
    ports: 
      - 3000:3000  
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - monitoring
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}  
      - GF_USERS_ALLOW_SIGN_UP=false
    # depends_on:
    #   - influxdb
    links:
      - influxdb
  
  node-red:
    image: nodered/node-red:1.3.5
    container_name: node-red
    user: ${MONITOR}
    environment:
       - TZ=Europe/Moscow
    ports:
       - "1880:1880"
    volumes:
       - ./node-red:/data
    networks:
       - monitoring
    restart: always
    links:
      - influxdb

  influxdb:
    image: influxdb:1.8.0
    container_name: influxdb
    ports:
       - "8086:8086"
    volumes:
       - ./influxdb:/var/lib/influxdb     
    networks:
       - monitoring
    restart: unless-stopped
    environment:
        - INFLUXDB_DB=${INFLUXDB_DB}
        - INFLUXDB_USER=${INFLUXDB_USER}
        - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
        # - INFLUXDB_ADMIN_ENABLED=true
        - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER} 
        - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}

networks:
  monitoring:
   driver: bridge
    
volumes:
    grafana: {}
    node-red: {}
    influxdb: {}

